# This assumes you have a hosts file with a group named
# ubuntu-servers. Change hosts: below to whatever is appropriate for
# your lists of hosts.
---
- name: Basic hardening of Ubuntu VM
  hosts: ubuntu-servers
  tasks:

    - name: update apt cache
      apt: update_cache=yes cache_valid_time=3600
      sudo: yes

    - name: upgrade the distro
      apt: upgrade=yes
      sudo: yes
    - name: install packages
      apt: pkg={{ item }} state=latest
      sudo: yes
      with_items:
        - fail2ban
        - chkrootkit
        - ufw
        - unattended-upgrades

    - name: ensure fail2ban is running
      sudo: yes
      action: service name=fail2ban state=restarted enabled=yes
    
    - name: forbid SSH root login
      sudo: yes
      lineinfile: destfile=/etc/ssh/sshd_config regexp="^PermitRootLogin without-password" line="PermitRootLogin no" state=present
      notify:
        - restart ssh

    - name: Forbid Password Authentication over ssh
      sudo: yes
      lineinfile: destfile=/etc/ssh/sshd_config regexp="^#?PasswordAuthentication.*" line="PasswordAuthentication no" state=present
      notify:
        - restart ssh

    - name: reset firewall
      sudo: yes
      action: shell ufw --force reset
    
    - name: allow firewall authorized ports
      sudo: yes
      action: shell ufw allow {{ item }} 
      with_items:
        - 22
        - 80
        - 443
    
    - name: enable firewall
      sudo: yes
      action: shell ufw --force enable
      
  handlers:

    - name: restart ssh
      sudo: yes
      action: service name=ssh state=restarted enabled=yes